export const ShopActionTypes = {
  SHOPS_FETCH_START: 'SHOPS_FETCH_START',
  SHOPS_FETCH_SUCCESS: 'SHOPS_FETCH_SUCCESS',
  SHOPS_FETCH_ERROR: 'SHOPS_FETCH_ERROR',
  CLEAR_SHOPS_FETCH_SUCCESS: 'CLEAR_SHOPS_FETCH_SUCCESS',

  SHOP_FETCH_START: 'SHOP_FETCH_START',
  SHOP_FETCH_SUCCESS: 'SHOP_FETCH_SUCCESS',
  SHOP_FETCH_ERROR: 'SHOP_FETCH_ERROR',
  CLEAR_SHOP_FETCH_SUCCESS: 'CLEAR_SHOP_FETCH_SUCCESS',

  SHOP_CREATE_START: 'SHOP_CREATE_START',
  SHOP_CREATE_SUCCESS: 'SHOP_CREATE_SUCCESS',
  SHOP_CREATE_ERROR: 'SHOP_CREATE_ERROR',
  CLEAR_SHOP_CREATE_SUCCESS: 'CLEAR_SHOP_CREATE_SUCCESS',

  SHOP_UPDATE_START: 'SHOP_UPDATE_START',
  SHOP_UPDATE_SUCCESS: 'SHOP_UPDATE_SUCCESS',
  SHOP_UPDATE_ERROR: 'SHOP_UPDATE_ERROR',
  CLEAR_SHOP_UPDATE_SUCCESS: 'CLEAR_SHOP_UPDATE_SUCCESS',

  SHOP_DELETE_START: 'SHOP_DELETE_START',
  SHOP_DELETE_SUCCESS: 'SHOP_DELETE_SUCCESS',
  SHOP_DELETE_ERROR: 'SHOP_DELETE_ERROR',
  CLEAR_SHOP_DELETE_SUCCESS: 'CLEAR_SHOP_DELETE_SUCCESS',
};
