export const EventActionTypes = {
  EVENTS_FETCH_START: 'EVENTS_FETCH_START',
  EVENTS_FETCH_SUCCESS: 'EVENTS_FETCH_SUCCESS',
  EVENTS_FETCH_ERROR: 'EVENTS_FETCH_ERROR',
  CLEAR_EVENTS_FETCH_SUCCESS: 'CLEAR_EVENTS_FETCH_SUCCESS',

  EVENT_FETCH_START: 'EVENT_FETCH_START',
  EVENT_FETCH_SUCCESS: 'EVENT_FETCH_SUCCESS',
  EVENT_FETCH_ERROR: 'EVENT_FETCH_ERROR',
  CLEAR_EVENT_FETCH_SUCCESS: 'CLEAR_EVENT_FETCH_SUCCESS',

  EVENT_CREATE_START: 'EVENT_CREATE_START',
  EVENT_CREATE_SUCCESS: 'EVENT_CREATE_SUCCESS',
  EVENT_CREATE_ERROR: 'EVENT_CREATE_ERROR',
  CLEAR_EVENT_CREATE_SUCCESS: 'CLEAR_EVENT_CREATE_SUCCESS',

  EVENT_UPDATE_START: 'EVENT_UPDATE_START',
  EVENT_UPDATE_SUCCESS: 'EVENT_UPDATE_SUCCESS',
  EVENT_UPDATE_ERROR: 'EVENT_UPDATE_ERROR',
  CLEAR_EVENT_UPDATE_SUCCESS: 'CLEAR_EVENT_UPDATE_SUCCESS',

  EVENT_DELETE_START: 'EVENT_DELETE_START',
  EVENT_DELETE_SUCCESS: 'EVENT_DELETE_SUCCESS',
  EVENT_DELETE_ERROR: 'EVENT_DELETE_ERROR',
  CLEAR_EVENT_DELETE_SUCCESS: 'CLEAR_EVENT_DELETE_SUCCESS',
};
