export const PlantActionTypes = {
  PLANTS_FETCH_START: 'PLANTS_FETCH_START',
  PLANTS_FETCH_SUCCESS: 'PLANTS_FETCH_SUCCESS',
  PLANTS_FETCH_ERROR: 'PLANTS_FETCH_ERROR',
  CLEAR_PLANTS_FETCH_SUCCESS: 'CLEAR_PLANTS_FETCH_SUCCESS',

  PLANT_FETCH_START: 'PLANT_FETCH_START',
  PLANT_FETCH_SUCCESS: 'PLANT_FETCH_SUCCESS',
  PLANT_FETCH_ERROR: 'PLANT_FETCH_ERROR',
  CLEAR_PLANT_FETCH_SUCCESS: 'CLEAR_PLANT_FETCH_SUCCESS',

  PLANT_CREATE_START: 'PLANT_CREATE_START',
  PLANT_CREATE_SUCCESS: 'PLANT_CREATE_SUCCESS',
  PLANT_CREATE_ERROR: 'PLANT_CREATE_ERROR',
  CLEAR_PLANT_CREATE_SUCCESS: 'CLEAR_PLANT_CREATE_SUCCESS',

  PLANT_UPDATE_START: 'PLANT_UPDATE_START',
  PLANT_UPDATE_SUCCESS: 'PLANT_UPDATE_SUCCESS',
  PLANT_UPDATE_ERROR: 'PLANT_UPDATE_ERROR',
  CLEAR_PLANT_UPDATE_SUCCESS: 'CLEAR_PLANT_UPDATE_SUCCESS',

  PLANT_DELETE_START: 'PLANT_DELETE_START',
  PLANT_DELETE_SUCCESS: 'PLANT_DELETE_SUCCESS',
  PLANT_DELETE_ERROR: 'PLANT_DELETE_ERROR',
  CLEAR_PLANT_DELETE_SUCCESS: 'CLEAR_PLANT_DELETE_SUCCESS',
};
