export const ApplyEventActionTypes = {
  APPLY_EVENT_START: 'APPLY_EVENT_START',
  APPLY_EVENT_SUCCESS: 'APPLY_EVENT_SUCCESS',
  APPLY_EVENT_ERROR: 'APPLY_EVENT_ERROR',
  CLEAR_APPLY_EVENT_SUCCESS: 'CLEAR_APPLY_EVENT_SUCCESS',
};
