export const IdentifyPlantActionTypes={
    IDENTIFY_PLANT_START:'IDENTIFY_PLANT_START',
    IDENTIFY_PLANT_SUCCESS:'IDENTIFY_PLANT_SUCCESS',
    IDENTIFY_PLANT_ERROR:'IDENTIFY_PLANT_ERROR',
    CLEAR_IDENTIFY_PLANT_SUCCESS:'CLEAR_IDENTIFY_PLANT_SUCCESS',
}
