export const AuthActionTypes = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  CLEAR_LOGIN_SUCCESS: 'CLEAR_LOGIN_SUCCESS',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  CLEAR_SIGN_UP_SUCCESS: 'CLEAR_SIGN_UP_SUCCESS',

  FORGOT_PASSWORD_START: 'FORGOT_PASSWORD_START',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',
  CLEAR_FORGOT_PASSWORD_SUCCESS: 'CLEAR_FORGOT_PASSWORD_SUCCESS',

  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
  CLEAR_RESET_PASSWORD_SUCCESS: 'CLEAR_RESET_PASSWORD_SUCCESS',

  GOOGLE_AUTH_START: 'GOOGLE_AUTH_START',
  GOOGLE_AUTH_SUCCESS: 'GOOGLE_AUTH_SUCCESS',
  GOOGLE_AUTH_ERROR: 'GOOGLE_AUTH_ERROR',

  LOG_OUT: 'LOGOUT',
};
